// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyrjtiuvxhdwsjjrlxtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cmp0aXV2eGhkd3NqanJseHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzYyMjMsImV4cCI6MjA2MTU1MjIyM30.QOMvmn_UK2GB6nP1XT6nyUaW43xVnqRWiyBwbf4fELE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);