name: Supabase Deploy Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -L -o supabase.tar.gz https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          if [ -z "$SUPABASE_ACCESS_TOKEN" ] || [ -z "$SUPABASE_PROJECT_REF" ]; then
            echo "Missing SUPABASE_ACCESS_TOKEN or SUPABASE_PROJECT_REF secrets" >&2
            exit 1
          fi
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          supabase link --project-ref "$SUPABASE_PROJECT_REF"
          supabase functions deploy --all

